### ISSUE TITLE
Update to use 0.9.8 Cloud Custodian release

### ISSUE THREAD

**Issue by fussybeaver** [manheim/manheim-c7n-tools#56]
We'd like to use a new feature added to CC 0.9.8 - can we get a bump in the Cloud Custodian dependency in Manheim with a release / docker tag? 
https://github.com/cloud-custodian/cloud-custodian/releases/tag/0.9.8.0

**Comment by jantman** [comment]
@fussybeaver we're hoping that https://github.com/cloud-custodian/cloud-custodian/pull/6249 will get merged to master in the next few days, at which point we'd likely bump to using the latest commit on master that includes it (unless there's an imminent release). If not, then we'll get a new version released with 0.9.8 soon.

**Comment by jantman** [comment]
@fussybeaver The PR that we've been waiting for has been merged upstream, and per the maintainer via Gitter chat, we should be expecting the 0.9.9 release within the next two weeks, and tentatively this coming Monday December 14. Once that comes out, we'll bump to it here.

**Comment by jantman** [comment]
This is currently blocked on (yet another) upstream dependency conflict: https://github.com/cloud-custodian/cloud-custodian/issues/6359

**Comment by jantman** [comment]
@fussybeaver The blocking upstream issue was fixed in yesterday's upstream release. This PR has been merged, and I hope to get a new release cut today, to include both this and #59 .

**Comment by fussybeaver** [comment]
nice, thanks

**Comment by jantman** [comment]
This has been released in 1.3.0, which is now live on PyPI and Docker Hub.
