### ISSUE TITLE
Logs not being written to output_s3_bucket_name

### ISSUE THREAD

**Issue by matticulous** [manheim/manheim-c7n-tools#57]
We are currently using runner to deploy our policies to our AWS accounts. In our config, we are setting the s3 bucket name to the name of the bucket (following the example config). However, no log output ever gets written to the bucket. Our policies are all configured as `mode: periodic` (lambda). In the lambda logs, I can see that log output is being written to file:///tmp/[policy_name]. Is there something that I need to be configuring differently? It looks like `execution-options` are being set for `metrics` and `log-group`, but nothing for `output_dir`.

**Comment by jantman** [comment]
Matt, yeah, you need to set ``output_dir`` in ``execution-options`` to a S3 URL. See [the example default.yml in this repo](https://github.com/manheim/manheim-c7n-tools/blob/master/example_config_repo/policies/defaults.yml#L6-L8) - in general, either your policy or your defaults.yml (wherever you specify execution-options) will generally need to look something like:

```yaml
  execution-options:
    log_group: '%%LOG_GROUP%%'
    output_dir: 's3://%%BUCKET_NAME%%/logs'
```

manheim-c7n-tools / runner will interpolate that with the log group and bucket names, but ``log_group`` and ``output_dir`` still need to be explicitly specified.

I'm going to close this issue now in the hope that the above solves your problem, but please feel free to reopen it if you need some more assistance.
